trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Todo_Build_Stage
  displayName: Todo_Build_Stage
  jobs:
  - job: Todo_Build_Stage
    displayName: Todo_Build_Stage
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
    - task: CmdLine@2
      inputs:
        script: |
          npm install
          npm run build
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'todoAvi'
        publishLocation: 'Container'
